### ISSUE TITLE
Is Visual Studio 2015 supported?

### ISSUE THREAD

**Issue by orSolocate** [viacheslav-lozinskyi/MetaProject#15]
Hey there,
On the readme file here it says VS2015 is supported, although I couldn't find the extension on VS2015 Extension and Updates window, Online tab.
Could it be added in VS2015 marketplace? or otherwise just fix the repo's readme.

**Comment by viacheslav-lozinskyi** [comment]
Ups, link from download page is incorrect.
It's already updated.
You can download extension [here](https://www.metaoutput.net/download).

This is direct link to old version of MetaOutput which support Visual Studio 2015.
In next release I plan to restore support of Visual Studio 2015 because many users continue use this version of IDE, and requested it.

Thank you for reported problem.

**Comment by orSolocate** [comment]
Thanks it works on my IDE now 👍
