### ISSUE TITLE
Allow font face customisation

### ISSUE THREAD

**Issue by gmatte11** [viacheslav-lozinskyi/MetaProject#2]
I can't seem to find a way to change the font (family, size, style, etc.) for the MetaProject window.

It should be an option as the current font is not monospaced and it breaks some of my project outputs alignment.

Add the option in the MetaProject option category, use the same as the Output Window or add a new settings group in the `Environment > Fonts and Colors` menu. As long as it's customisable.

**Comment by viacheslav-lozinskyi** [comment]
MetaProject should look like as native tool for Visual Studio, and therefore it uses standard colors and standard fonts of this IDE. 
It was a reason why additional customization for fonts and colors was not added and will not be added. MetaProject uses default font, but will be more correct to use "Output Window" font, and I agree to change this font, because it is reasonable.
However it will be not in nearest releases, because I am working on more important functionality now.
In any case, thanks for your request.
